reset;

model benders.mod;
data instances_csp/small.ampl;

option solver cplex;
#option cplex_options 'presolve=0 chk:feastol=1e-9 sol:chk:prec=20';
option cplex_options 'presolve=0';

problem Master: y, z, Total_Cost, Cuts;
problem Sub: alpha_l, alpha_u, gamma_l, gamma_u, lambda_l, lambda_u, mu_l, mu_u, Subproblem_Cost, Conservation_L, Conservation_U;

suffix unbdd OUT;

let NCuts := 0;
    
for {i in I} let Y[i] := is_p[i];

param GAP default Infinity;
param epsilon default 1.0e-8;
let z := 1000000;

repeat {
    printf "-------------------------------------------------------\n";
    printf "Iteration %d\n", NCuts + 1;
    printf "-------------------------------------------------------\n";
    
    printf "Solving Subproblem\n";
    solve Sub;
    display Sub.result, Subproblem_Cost;

    let NCuts := NCuts + 1;
    if Sub.result = "unbounded" then {
        printf "Subproblem Unbounded -> Adding Ray Cut\n";

        
        let CutType[NCuts] := "ray";
        let Gamma[NCuts] := sum {px in P} (plpl[px] * gamma_l[px].unbdd + pupl[px] * gamma_u[px].unbdd);
        let {i in I} Lambda[NCuts, i] := sum {px in P} (
        	(lb[i] - a[i]) * lambda_l[px, i].unbdd -
        	(ub[i] - a[i]) * mu_l[px, i].unbdd +
        	(lb[i] - a[i]) * lambda_u[px, i].unbdd -
        	(ub[i] - a[i]) * mu_u[px, i].unbdd
        	);
    }
    else {
        if z <= epsilon then break;
        
        printf "Subproblem Solved -> Adding Point Cut\n";

        let CutType[NCuts] := "point";
        let Gamma[NCuts] := sum {px in P} (plpl[px] * gamma_l[px] + pupl[px] * gamma_u[px]);
        let {i in I} Lambda[NCuts, i] := sum {px in P} (
        	(lb[i] - a[i]) * lambda_l[px, i] -
        	(ub[i] - a[i]) * mu_l[px, i] +
        	(lb[i] - a[i]) * lambda_u[px, i] -
        	(ub[i] - a[i]) * mu_u[px, i]
        	);
    }
    
    printf "\nSolving Master Problem\n";
    solve Master;
    expand Master;
    
    display Master.result, y, z, Total_Cost;
    
    for {i in I} let Y[i] := y[i];
}